export const SITE = {
  name: "Dilukshan Niranjan",
  url: "https://dilukshan.dev",
  title: "Dilukshan Niranjan | Full-Stack Developer, AI Engineer",
  description:
    "Dilukshan Niranjan is a Sri Lankan full-stack developer and AI engineer building fast web applications, production AI systems, and polished digital products.",
  blogTitle: "Dilukshan Niranjan Blog | Engineering, AI & Web Development",
  blogDescription:
    "Essays and technical notes on Astro, full-stack engineering, AI product delivery, web performance, and building polished developer-first experiences.",
  locale: "en_US",
  language: "en",
  author: "Dilukshan Niranjan",
  profession: "Full-Stack Developer & AI Engineer",
  email: "info@dilukshan.dev",
  location: "Sri Lanka",
  themeColor: "#050505",
  keywords: [
    "Dilukshan Niranjan",
    "Dilukshan Niranjan portfolio",
    "Dilukshan portfolio",
    "full-stack developer",
    "fullstack developer",
    "AI engineer",
    "software engineer portfolio",
    "Astro developer portfolio",
    "developer blog",
    "Astro SEO",
    "AI engineering blog",
    "Sri Lanka developer",
    "software engineer",
    "web developer",
    "portfolio website",
    "Astro portfolio",
  ],
  twitterHandle: "@dilukshann7",
  socialImage: "/fallbacks/galaxy.jpg",
  socialImageAlt: "Dilukshan Niranjan portfolio preview",
  availability: "Open to freelance, contract, and product collaborations",
  resumeRequestHref:
    "mailto:info@dilukshan.dev?subject=Resume%20Request%20-%20Dilukshan%20Niranjan",
  focusAreas: [
    "AI-assisted SaaS products",
    "Internal tools and dashboards",
    "High-craft frontend systems",
  ],
  sameAs: [
    "https://github.com/dilukshann7",
    "https://linkedin.com/in/dilukshann7",
    "https://x.com/silknye",
    "https://instagram.com/silknye",
  ],
} as const;
